### ISSUE TITLE
1. Making A Plan!

### ISSUE THREAD

**Issue by Sukhrobjon** [MakeSchool-Tutorials/We-Sell-Shoes#5]
I think my comment was not shown correctly. I mean when we link css file inside html we declared it as re="stylesheet" href="./styles.css". this is how it is written on tutorial
but I had a problem with that  and then when I wrote it as rel="stylesheet" href="./styles.css" and it worked. I am not if this can be considered as en error. I have zero html experience

**Comment by joerez** [comment]
Can you be more descriptive of what should be what?
